force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TestLocationCtrl.cls
@isTest 
public class TestLocationCtrl{
    static testMethod void UnitTest() {
        Location__c Loc = new Location__c();
        Loc.Street__c = 'street';
        Loc.State__c = 'state';
        Loc.Country__c = 'country';
        Loc.City__c  = 'city';
        Loc.Postal_Code__c = '00112233';
        Loc.Active__c = true;
        Loc.Coordinates__Latitude__s = 77.000000;
        LOc.Coordinates__Longitude__s = 102.000000;
        try{
           insert Loc;    
        }catch(Exception e){
            system.assertEquals(e.getMessage().contains('Please Enter Valid Address Details'),false);
        }
        
        LocationCtrl objLocation = new LocationCtrl();
        objLocation.locationId = Loc.Id;
        objLocation.goToNewEditMode();
        objLocation.cancelNewEditMode();
        objLocation.saveLocation();
        objLocation.locationIdForDelete = Loc.Id;
        objLocation.DeleteLocation();
        objLocation.Search();
    }
    
    static testMethod void UnitTest1() {
        Location__c Loc = new Location__c();
        Loc.Street__c = 'street';
        Loc.State__c = 'state';
        Loc.Country__c = 'country';
        Loc.City__c  = 'city';
        Loc.Postal_Code__c = '00112233';
        Loc.Active__c = true;
        try{
           insert Loc;    
        }catch(Exception e){
            system.assertEquals(e.getMessage().contains('Please Enter Valid Address Details'),true);
        }
        LocationCtrl objLocation = new LocationCtrl();
        objLocation.locationId = Loc.Id;
        objLocation.goToNewEditMode();
        objLocation.cancelNewEditMode();
        objLocation.saveLocation();
        objLocation.locationIdForDelete = Loc.Id;
        objLocation.Search();
        objLocation.DeleteLocation();
    }
}