force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>Noti-{0000000000}</displayFormat>
        <label>Notification No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/view__c.field-meta.xml
<CustomField>
    <fullName>view__c</fullName>
    <defaultValue>false</defaultValue>
    <label>view</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotificationCtrl.cls
global with sharing class NotificationCtrl{
    
    public NotificationCtrl(){
        
    }
    
    global class Notifications{
        public string notificationId{get;set;}
        public string description{get;set;} 
        public boolean read{get;set;}
        public boolean view{get;set;}
        public string contactId{get;set;}
    }
    
    @RemoteAction
    global static Integer getNotificationCount(){
        Integer notificationCount;
        list<AggregateResult> lstAgg=new list<AggregateResult>();
        if(Schema.sObjectType.Notification__c.fields.view__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()){
            lstAgg=[SELECT  Count(id) notiCount,view__c v,contact__c con FROM Notification__c WHERE view__c = false And read__c = false GROUP BY contact__c,view__c] ;  
        }
        if(lstAgg.size() > 0){
            for (AggregateResult ar : lstAgg){
                notificationCount = (Integer)ar.get('notiCount');
            } 
        }
        return notificationCount;
    }
    
    @RemoteAction
    global static List<Notifications> getNotification(){
        Notifications noti;
        List<Notifications> notificationModel = new List<Notifications>();
        List<Notification__c> notificationList = new List<Notification__c>();
        if(Schema.sObjectType.Notification__c.fields.view__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()
            && Schema.sObjectType.Notification__c.fields.read__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Description__c.isAccessible()){
            notificationList = [SELECT id,read__c,Description__c, view__c,contact__c  FROM Notification__c where contact__c  != null And read__c = false order by createddate desc];
        }
        
        for(Notification__c n: notificationList){
            noti = new Notifications();
            noti.description = n.Description__c;
            noti.read = n.read__c;
            noti.view = n.view__c;
            noti.notificationId = n.id;
            noti.contactId = n.contact__c;
            notificationModel.add(noti);
        }
        return notificationModel;
    } 
    
    @RemoteAction
    global static void CheckAllNotification(){
        List<Notification__c> notiList = new List<Notification__c>();
        List<Notification__c> notiListTemp = new List<Notification__c>();
        if(Schema.sObjectType.Notification__c.fields.view__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()
            && Schema.sObjectType.Notification__c.fields.read__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Description__c.isAccessible()){
            
            notiList = [SELECT id,read__c,Description__c, view__c,contact__c  FROM Notification__c WHERE view__c = false and read__c = false];
        }
        for(Notification__c n: notiList){
            n.view__c = true;
            notiListTemp.add(n); 
        }
        if(notiListTemp.size()>0){
            if((Schema.sObjectType.Notification__c.fields.view__c.isCreateable() && Schema.sObjectType.Notification__c.fields.Contact__c.isCreateable()
            && Schema.sObjectType.Notification__c.fields.read__c.isCreateable() && Schema.sObjectType.Notification__c.fields.Description__c.isCreateable()) && (Schema.sObjectType.Notification__c.fields.view__c.isUpdateable() && Schema.sObjectType.Notification__c.fields.Contact__c.isUpdateable()
            && Schema.sObjectType.Notification__c.fields.read__c.isUpdateable() && Schema.sObjectType.Notification__c.fields.Description__c.isUpdateable())){
            
                update notiListTemp;
            }
        }
    }
    
    @RemoteAction
    global static void CheckReadNotification(string notiId){
        System.debug('Notification Ids'+ notiId);
        List<Notification__c> notiList = new List<Notification__c>();
        List<Notification__c> notiListTemp = new List<Notification__c>();
        if(Schema.sObjectType.Notification__c.fields.view__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()
            && Schema.sObjectType.Notification__c.fields.read__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Description__c.isAccessible()){
            
            notiList = [SELECT id,read__c,Description__c, view__c,contact__c  FROM Notification__c WHERE id =: notiId];
        }
        for(Notification__c n: notiList){
            n.read__c = true;
            notiListTemp.add(n); 
        }
        if(notiListTemp.size()>0){
            if(Schema.sObjectType.Notification__c.fields.read__c.isUpdateable()){
                 system.debug('Update');
                 try{
                update notiListTemp;
                }
                catch(Exception e){
                 system.debug('Exception'+e);
                }
            }
        }
    }
    
    
    @RemoteAction
    global static void ClearAllNotification( string conId){
        List<Notification__c> notiList = new List<Notification__c>();
        if(Schema.sObjectType.Notification__c.fields.view__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()
            && Schema.sObjectType.Notification__c.fields.read__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Description__c.isAccessible()){
            
            notiList = [SELECT id,read__c,Description__c, view__c,contact__c  FROM Notification__c WHERE contact__c =: conId];
        }
        if(Notification__c.sObjectType.getDescribe().isDeletable()){
            delete notiList;
        }
    }
    
}