force-app/main/default/objects/UIpanel__c/UIpanel__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>UI Panel</label>
</CustomObject>

force-app/main/default/objects/UIpanel__c/fields/Header_BG_Color__c.field-meta.xml
<CustomField>
    <fullName>Header_BG_Color__c</fullName>
    <defaultValue>&quot;header-bg7&quot;</defaultValue>
    <label>Header BG Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UIpanel__c/fields/Logo_Color_BG__c.field-meta.xml
<CustomField>
    <fullName>Logo_Color_BG__c</fullName>
    <defaultValue>&quot;logo-bg2&quot;</defaultValue>
    <label>Logo Color BG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAddColorDashboard.cls
@isTest 
public class TestAddColorDashboard{
    static testMethod void UnitTest() {
        UIpanel__c ObjUi = new UIpanel__c();
        objUI.Logo_Color_BG__c = 'logo-bg2';
        objUI.Header_BG_Color__c = 'header-bg1';
        objUI.SetupOwnerId= Userinfo.getUserId();
        insert objUI;
          System.assertEquals(objUI.SetupOwnerId,Userinfo.getUserId());
        AddColorDashboard obj = new AddColorDashboard();
        obj.getColorList();
        obj.saveDashboard();
    }
}