force-app/main/default/objects/Contact/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Staff.recordType-meta.xml
<RecordType>
    <fullName>Staff</fullName>
    <active>true</active>
    <label>Staff</label>
</RecordType>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Padding_Time__c.field-meta.xml
<CustomField>
    <fullName>Padding_Time__c</fullName>
    <label>Padding Time</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AppointmentHelper.cls
public with sharing class AppointmentHelper{

    public static list<location__c> fetchAllLocations(){
        if(Schema.sObjectType.Location__c.fields.name.isAccessible() && Schema.sObjectType.Location__c.fields.Street__c.isAccessible() && Schema.sObjectType.Location__c.fields.Country__c.isAccessible()
           && Schema.sObjectType.Location__c.fields.City__c.isAccessible() && Schema.sObjectType.Location__c.fields.Postal_Code__c.isAccessible()
           && Schema.sObjectType.Location__c.fields.Coordinates__Latitude__s.isAccessible() && Schema.sObjectType.Location__c.fields.Coordinates__Longitude__s.isAccessible()){
            return [select name,Street__c,State__c,Country__c,City__c,Postal_Code__c,Coordinates__Latitude__s,Coordinates__Longitude__s from Location__c where id != null];
        }
        return null;
    }
    
    public static list<location__c> fetchActiveLocation(){
        if(Schema.sObjectType.Location__c.fields.name.isAccessible() && Schema.sObjectType.Location__c.fields.Street__c.isAccessible() && Schema.sObjectType.Location__c.fields.Country__c.isAccessible()
           && Schema.sObjectType.Location__c.fields.City__c.isAccessible() && Schema.sObjectType.Location__c.fields.Postal_Code__c.isAccessible()
           && Schema.sObjectType.Location__c.fields.Coordinates__Latitude__s.isAccessible() && Schema.sObjectType.Location__c.fields.Coordinates__Longitude__s.isAccessible()){
            return [select name,Street__c,State__c,Country__c,City__c,Postal_Code__c,Coordinates__Latitude__s,Coordinates__Longitude__s from Location__c where id != null];
        }
        return null;
    }
    
    
    public static list<Service__c> fetchAllServices(){
        
        if(Schema.sObjectType.Service__c.fields.name.isAccessible() && Schema.sObjectType.Service__c.fields.Description__c.isAccessible() && Schema.sObjectType.Service__c.fields.Duration__c.isAccessible() 
         && Schema.sObjectType.Service__c.fields.Padding_Time__c.isAccessible() && Schema.sObjectType.Service__c.fields.Price__c.isAccessible()){
            return [select name,Description__c,Duration__c,Padding_Time__c,Price__c from Service__c where id != null];
        }
        return null;
    }
    
    public static list<Service__c> fetchActiveServices(){
        if(Schema.sObjectType.Service__c.fields.name.isAccessible() && Schema.sObjectType.Service__c.fields.Description__c.isAccessible() && Schema.sObjectType.Service__c.fields.Duration__c.isAccessible() 
         && Schema.sObjectType.Service__c.fields.Padding_Time__c.isAccessible() && Schema.sObjectType.Service__c.fields.Price__c.isAccessible()){
            return [select name,Description__c,Duration__c,Padding_Time__c,Price__c from Service__c where id != null];
        }
        return null;
    }
    
    
  /*  public static list<contact> fetchAllResourceStaffUsers(){
        if(Schema.sObjectType.contact.fields.name.isAccessible() && Schema.sObjectType.contact.fields.Capacity__c.isAccessible()
        && Schema.sObjectType.contact.fields.Languages__c.isAccessible() && Schema.sObjectType.contact.fields.Level__c.isAccessible() && Schema.sObjectType.contact.fields.Phone.isAccessible()
        && Schema.sObjectType.contact.fields.MailingCity.isAccessible() && Schema.sObjectType.contact.fields.MailingCountry.isAccessible() && Schema.sObjectType.contact.fields.MailingState.isAccessible()
        && Schema.sObjectType.contact.fields.MailingStreet.isAccessible() && Schema.sObjectType.contact.fields.MailingPostalCode.isAccessible() && Schema.sObjectType.contact.fields.location__c.isAccessible()){
            return [select name,RecordType.Name,Capacity__c,Languages__c,Level__c,Phone,MailingCity,MailingCountry,
                    MailingState,MailingStreet,MailingPostalCode,location__c from contact where RecordType.Name IN ('Resource', 'Staff')];
        }
        return null;
    }*/
    
    public static list<contact> fetchAllResourceStaff(){
        if(Schema.sObjectType.contact.fields.name.isAccessible() && Schema.sObjectType.contact.fields.Capacity__c.isAccessible()
        && Schema.sObjectType.contact.fields.Languages__c.isAccessible() && Schema.sObjectType.contact.fields.Level__c.isAccessible() && Schema.sObjectType.contact.fields.Phone.isAccessible()
        && Schema.sObjectType.contact.fields.MailingCity.isAccessible() && Schema.sObjectType.contact.fields.MailingCountry.isAccessible() && Schema.sObjectType.contact.fields.MailingState.isAccessible()
        && Schema.sObjectType.contact.fields.MailingStreet.isAccessible() && Schema.sObjectType.contact.fields.MailingPostalCode.isAccessible() && Schema.sObjectType.contact.fields.location__c.isAccessible()){
            return [select name,RecordType.Name,Capacity__c,Languages__c,Level__c,Phone,MailingCity,MailingCountry,
                    MailingState,MailingStreet,MailingPostalCode,location__c from contact where RecordType.Name IN ('Resource', 'Staff')];
        }
        return null;
        
    }
}