force-app/main/default/objects/Contact/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>Noti-{0000000000}</displayFormat>
        <label>Notification No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/TestNotificationCtrl.cls
@isTest 
public class TestNotificationCtrl{
    static testMethod void UnitTest() {
        contact newCon = new contact();
        newCon.lastname= 'Jams Smith';
        newCon.Capacity__c = 0;
        newCon.Languages__c = 'English';
        insert newCon;
        
        Notification__c obj = new Notification__c();
        obj.Contact__c = newCon.Id;
        obj.Description__c = 'Appointment Created';
        insert obj;
        NotificationCtrl.getNotificationCount();
        System.assertEquals([select id,name from Notification__c].size(),1);
        NotificationCtrl.getNotification();
        NotificationCtrl.CheckAllNotification();
        
        NotificationCtrl.CheckReadNotification(obj.id);
        NotificationCtrl.ClearAllNotification(newCon.id);
    }
}