force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Service_Alignment__c/Resource_Service_Alignment__c.object-meta.xml
<CustomObject>
    <label>Resource/Service Alignment</label>
    <nameField>
        <label>Resource/Service Alignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource/Service Alignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Resource/Service Alignments</relationshipLabel>
    <relationshipName>Resource_Service_Alignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Resource_Staff__c.field-meta.xml
<CustomField>
    <fullName>Resource_Staff__c</fullName>
    <label>Resource/Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Business_Alignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Service</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/Resource_Staff_Time__c.object-meta.xml
<CustomObject>
    <label>Resource/Staff Time Allocation</label>
    <nameField>
        <displayFormat>RSTA-{00000}</displayFormat>
        <label>Resource/Staff Time Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource/Staff Time Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Staff_Time__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Friday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Resource_Business_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Resource_Business_Alignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource/Business Alignment</label>
    <referenceTo>Resource_Service_Alignment__c</referenceTo>
    <relationshipLabel>Resource_Staff_Time</relationshipLabel>
    <relationshipName>Resource_Staff_Time_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Saturday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sunday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tuesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource_Staff_Time__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wednesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ResourceStaffTimeAllocation.cls
public with sharing class ResourceStaffTimeAllocation{
    public string AlignmentId {get;set;}
    public string AllocationId{get;set;}
    public Resource_Service_Alignment__c Alignment{get;set;}
    public List<Resource_Staff_Time__c> resourceTimeList{get;set;}
    public Resource_Staff_Time__c resourceTime {get;set;}
    public ResourceStaffTimeAllocation(){
        AlignmentId = ApexPages.currentPage().getParameters().get('id');
        if(AlignmentId != null){
            Alignment = new Resource_Service_Alignment__c();
            if(Schema.sObjectType.Resource_Service_Alignment__c.fields.name.isAccessible() && Schema.sObjectType.Resource_Service_Alignment__c.fields.Service__c.isAccessible()
            && Schema.sObjectType.Resource_Service_Alignment__c.fields.Resource_Staff__c.isAccessible() && Schema.sObjectType.Resource_Service_Alignment__c.fields.Location__c.isAccessible()
            && Schema.sObjectType.Service__c.fields.name.isAccessible() && Schema.sObjectType.Location__c.fields.name.isAccessible() && Schema.sObjectType.contact.fields.name.isAccessible()){
                Alignment = [select name,Service__r.name,Resource_Staff__r.name,Location__r.name from Resource_Service_Alignment__c where id =: AlignmentId];
            }
            resourceTimeList = new List<Resource_Staff_Time__c>();
            resourceTimeList =getResourceTimeList(AlignmentId);
        }
        System.debug('--- resourceList'+resourceTimeList);
    }
    public static List<Resource_Staff_Time__c> getResourceTimeList(string AlignmentId){
        if(Schema.sObjectType.Resource_Staff_Time__c.fields.name.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Start_Date_Time__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.End_Date_Time__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Resource_Business_Alignment__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Active__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Monday__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Tuesday__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Wednesday__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Thursday__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Friday__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Saturday__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Sunday__c.isAccessible()){
           return [select Name,Start_Date_Time__c,End_Date_Time__c, Resource_Business_Alignment__c,
                                   Active__c,Monday__c,Tuesday__c,Wednesday__c,Thursday__c,Friday__c,Saturday__c,Sunday__c 
                                   from Resource_Staff_Time__c where Resource_Business_Alignment__c =:AlignmentId];
       }
       return null;
    }
    public void goToNewEditMode(){
        if(AllocationId == ''){
            resourceTime = new Resource_Staff_Time__c();
        }else{
            if(Schema.sObjectType.Resource_Staff_Time__c.fields.name.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Start_Date_Time__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.End_Date_Time__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Resource_Business_Alignment__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Active__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Monday__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Tuesday__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Wednesday__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Thursday__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Friday__c.isAccessible()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Saturday__c.isAccessible() && Schema.sObjectType.Resource_Staff_Time__c.fields.Sunday__c.isAccessible()){
            
                resourceTime = [select Name,Start_Date_Time__c,End_Date_Time__c, Resource_Business_Alignment__c,
                                   Active__c,Monday__c,Tuesday__c,Wednesday__c,Thursday__c,Friday__c,Saturday__c,Sunday__c 
                                   from Resource_Staff_Time__c where id =:AllocationId];
           }
        }
    }
    
    public void saveAllocation(){
        if(AlignmentId == '')
            resourceTime.Resource_Business_Alignment__c = AlignmentId;
        if((Schema.sObjectType.Resource_Staff_Time__c.fields.name.isCreateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Start_Date_Time__c.isCreateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.End_Date_Time__c.isCreateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Resource_Business_Alignment__c.isCreateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Active__c.isCreateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Monday__c.isCreateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Tuesday__c.isCreateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Wednesday__c.isCreateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Thursday__c.isCreateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Friday__c.isCreateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Saturday__c.isCreateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Sunday__c.isCreateable())
            && (Schema.sObjectType.Resource_Staff_Time__c.fields.name.isUpdateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Start_Date_Time__c.isUpdateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.End_Date_Time__c.isUpdateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Resource_Business_Alignment__c.isUpdateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Active__c.isUpdateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Monday__c.isUpdateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Tuesday__c.isUpdateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Wednesday__c.isUpdateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Thursday__c.isUpdateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Friday__c.isUpdateable()
            && Schema.sObjectType.Resource_Staff_Time__c.fields.Saturday__c.isUpdateable() && Schema.sObjectType.Resource_Staff_Time__c.fields.Sunday__c.isUpdateable())){
            
            upsert resourceTime;
        }
        resourceTimeList =getResourceTimeList(AlignmentId);
        System.debug('--- resourceList'+resourceTimeList);
    }
}