force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <formula>Resource_Service_Alignment__r.Resource_Staff__r.Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Resource_Service_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Resource_Service_Alignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource/Service Alignment</label>
    <referenceTo>Resource_Service_Alignment__c</referenceTo>
    <relationshipLabel>Resource/Service</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name__c</fullName>
    <label>Participant Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/Resource_Service_Alignment__c.object-meta.xml
<CustomObject>
    <label>Resource/Service Alignment</label>
    <nameField>
        <label>Resource/Service Alignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource/Service Alignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Resource/Service Alignments</relationshipLabel>
    <relationshipName>Resource_Service_Alignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Resource_Staff__c.field-meta.xml
<CustomField>
    <fullName>Resource_Staff__c</fullName>
    <label>Resource/Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Business_Alignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Service</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Chargable__c.field-meta.xml
<CustomField>
    <fullName>Chargable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chargable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Padding_Time__c.field-meta.xml
<CustomField>
    <fullName>Padding_Time__c</fullName>
    <label>Padding Time</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestAppointmentCtrl.cls
@isTest 
public class TestAppointmentCtrl{
    static testMethod void UnitTest() {
        
        Location__c Loc = new Location__c();
        Loc.Street__c = 'street';
        Loc.State__c = 'state';
        Loc.Country__c = 'country';
        Loc.City__c  = 'city';
        Loc.Postal_Code__c = '00112233';
        Loc.Active__c = true;
        Loc.Coordinates__Latitude__s = 77.000000;
        Loc.Coordinates__Longitude__s = 102.000000;
        insert Loc;
        
        Location__c Loc1 = new Location__c();
        Loc1.Street__c = 'street1';
        Loc1.State__c = 'state1';
        Loc1.Country__c = 'country1';
        Loc1.City__c  = 'city1';
        Loc1.Postal_Code__c = '00112233';
        Loc1.Active__c = true;
        Loc1.Coordinates__Latitude__s = 77.000000;
        Loc1.Coordinates__Longitude__s = 102.000000;
        insert Loc1;
        
        string strloc = string.valueOf(loc.id);
        string strloc1 = string.valueOf(loc1.id);
        
        contact newCon = new contact();
        newCon.lastname= 'Jams Smith';
        newCon.Capacity__c = 0;
        newCon.Languages__c = 'English';
        newCon.location__c = strloc  +';'+strloc1+';'; 
        insert newCon;
        
        Service__c  newService = new Service__c ();
        newService.Name = 'My service';
        newService.Description__c = 'Service Description';
         
        newService.Duration__c = 5;
        newService.Padding_Time__c = 10;
        newService.Price__c = 1200;
        newService.Active__c = true;
        newService.Chargable__c = true;
        
        insert newService;
        
        Resource_Service_Alignment__c ali = new Resource_Service_Alignment__c();
        ali.Resource_Staff__c = newCon.id;
        ali.Service__c = newService.id;
        ali.Location__c = Loc.Id;
        insert ali;
        
        system.assertEquals(ali.Service__c, newService.id);
        system.assertEquals(ali.Location__c, Loc.id);
        
        Appointment__c appObj = new Appointment__c();
        appObj.Start_Date_Time__c = System.now();
        appObj.End_Date_Time__c = system.now().addMinutes(1);
        appObj.Discount__c = 5;
        appObj.Resource_Service_Alignment__c = ali.id;
        insert appObj;
        
        Participant__c parObj = new Participant__c ();
        parObj.Appointment__c = appObj.id;
        parObj.Participant_Name__c = newCon.id;
        insert parObj;
        
        Appointment__c appObj1 = new Appointment__c();
        appObj1.Start_Date_Time__c = System.now();
        appObj1.End_Date_Time__c = system.now().addMinutes(1);
        insert appObj1;
        
        ApexPages.currentPage().getParameters().put('id', appObj.id+','+appObj1.id);
        AppointmentCtrl obj = new AppointmentCtrl();
        obj.SelectedApppointmentId = appObj.id;
        obj.SelectedAppointment();
        obj.selectedLocation = Loc.id;        
        obj.fetchServiceBasedOnLocation();
        obj.selectedService = newService.id;
        obj.fetchProviderBasedOnService();
        obj.getLocationList();
        obj.getServiceList();
        obj.getServiceDuration();
        obj.getProviderList();
        obj.selectedProvider = newCon.id;
        obj.getPriceBasedOnService();
        obj.getTotalPrice();
        obj.startTime = '10:00:AM';
        obj.startDate = '2015-10-07';
        obj.saveAppointment();
        obj.fetchParticipant();
        obj.addParticipant();
        obj.search();
        obj.removeParticipant();
        
        obj.cloneExistingRecord(); 
        obj.saveCustomer();     
    }
    
    
    static testMethod void TestSaveAppointment() {
        
        Location__c Loc = new Location__c();
        Loc.Street__c = 'street';
        Loc.State__c = 'state';
        Loc.Country__c = 'country';
        Loc.City__c  = 'city';
        Loc.Postal_Code__c = '00112233';
        Loc.Active__c = true;
        Loc.Coordinates__Latitude__s = 77.000000;
        Loc.Coordinates__Longitude__s = 102.000000;
        insert Loc;
           
        AppointmentCtrl app = new AppointmentCtrl();
        app.selectedLocation = Loc.Id;
        
        app.saveAppointment();
        
    }
    
    static testMethod void TestSaveAppointmentForNoLocation() {
        
        Service__c  newService = new Service__c ();
        newService.Name = 'My service';
        newService.Description__c = 'Service Description';
         
        newService.Duration__c = 5;
        newService.Padding_Time__c = 10;
        newService.Price__c = 1200;
        newService.Active__c = true;
        newService.Chargable__c = true;
        
        insert newService;
           
        AppointmentCtrl app = new AppointmentCtrl();
        app.selectedService = newService.Id;
        
        app.saveAppointment();
        
    }
    
     static testMethod void TestSaveAppointmentForNoProvider() {
        
        Service__c  newService = new Service__c ();
        newService.Name = 'My service';
        newService.Description__c = 'Service Description';
         
        newService.Duration__c = 5;
        newService.Padding_Time__c = 10;
        newService.Price__c = 1200;
        newService.Active__c = true;
        newService.Chargable__c = true;
        
        insert newService;
         
         
        Location__c Loc = new Location__c();
        Loc.Street__c = 'street';
        Loc.State__c = 'state';
        Loc.Country__c = 'country';
        Loc.City__c  = 'city';
        Loc.Postal_Code__c = '00112233';
        Loc.Active__c = true;
        Loc.Coordinates__Latitude__s = 77.000000;
        Loc.Coordinates__Longitude__s = 102.000000;
        insert Loc;
           
        AppointmentCtrl app = new AppointmentCtrl();
        app.selectedService = newService.Id;
        app.selectedLocation = Loc.Id;
        app.saveAppointment();
        
    }
    
    static testMethod void TestSaveAppointmentForNoStartTime() {
        
        Service__c  newService = new Service__c ();
        newService.Name = 'My service';
        newService.Description__c = 'Service Description';
         
        newService.Duration__c = 5;
        newService.Padding_Time__c = 10;
        newService.Price__c = 1200;
        newService.Active__c = true;
        newService.Chargable__c = true;
        
        insert newService;
         
         
        Location__c Loc = new Location__c();
        Loc.Street__c = 'street';
        Loc.State__c = 'state';
        Loc.Country__c = 'country';
        Loc.City__c  = 'city';
        Loc.Postal_Code__c = '00112233';
        Loc.Active__c = true;
        Loc.Coordinates__Latitude__s = 77.000000;
        Loc.Coordinates__Longitude__s = 102.000000;
        insert Loc;
        
        contact newCon = new contact();
        newCon.lastname= 'Jams Smith';
        newCon.Capacity__c = 0;
        newCon.Languages__c = 'English';
        
        insert newCon;
           
        AppointmentCtrl app = new AppointmentCtrl();
        app.selectedService = newService.Id;
        app.selectedLocation = Loc.Id;
        app.selectedProvider = newCon.Id;
        app.saveAppointment();
        
    }
    
    static testMethod void TestSaveAppointmentForNoEndTime() {
        
        Service__c  newService = new Service__c ();
        newService.Name = 'My service';
        newService.Description__c = 'Service Description';
         
        newService.Duration__c = 5;
        newService.Padding_Time__c = 10;
        newService.Price__c = 1200;
        newService.Active__c = true;
        newService.Chargable__c = true;
        
        insert newService;
         
         
        Location__c Loc = new Location__c();
        Loc.Street__c = 'street';
        Loc.State__c = 'state';
        Loc.Country__c = 'country';
        Loc.City__c  = 'city';
        Loc.Postal_Code__c = '00112233';
        Loc.Active__c = true;
        Loc.Coordinates__Latitude__s = 77.000000;
        Loc.Coordinates__Longitude__s = 102.000000;
        insert Loc;
        
        contact newCon = new contact();
        newCon.lastname= 'Jams Smith';
        newCon.Capacity__c = 0;
        newCon.Languages__c = 'English';
        
        insert newCon;
           
        AppointmentCtrl app = new AppointmentCtrl();
        app.selectedService = newService.Id;
        app.selectedLocation = Loc.Id;
        app.selectedProvider = newCon.Id;
        app.startDate = '2015-10-07';
        app.fromCloneButton = true;
        app.checkDobuleBooking = false;
        app.saveAppointment();
        
    }
    
    
    
}