force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestCalendarCtrl.cls
@isTest 
public class TestCalendarCtrl{
    static testMethod void UnitTest() {
        Appointment__c appObj = new Appointment__c();
        appObj.Start_Date_Time__c = System.now();
        appObj.End_Date_Time__c = system.now().addMinutes(1);
        insert appObj;
         System.assertEquals([select id,name from Appointment__c].size(),1);
        CalendarCtrl obj = new CalendarCtrl();
        CalendarCtrl.fetchAllAppointmentSlotsJSON( UserInfo.getTimeZone().getID());
        obj.startDate = date.today();
        obj.searchAgenda();
       
    }
}