force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Resource_Service_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Resource_Service_Alignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource/Service Alignment</label>
    <referenceTo>Resource_Service_Alignment__c</referenceTo>
    <relationshipLabel>Resource/Service</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Service__c/Location_Service__c.object-meta.xml
<CustomObject>
    <label>Location/Service</label>
    <nameField>
        <displayFormat>LS-{0000}</displayFormat>
        <label>Location/Service Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location/Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Location/Services</relationshipLabel>
    <relationshipName>Location_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Location/Services</relationshipLabel>
    <relationshipName>Location_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>Noti-{0000000000}</displayFormat>
        <label>Notification No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/Resource_Service_Alignment__c.object-meta.xml
<CustomObject>
    <label>Resource/Service Alignment</label>
    <nameField>
        <label>Resource/Service Alignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource/Service Alignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Resource/Service Alignments</relationshipLabel>
    <relationshipName>Resource_Service_Alignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Resource_Staff__c.field-meta.xml
<CustomField>
    <fullName>Resource_Staff__c</fullName>
    <label>Resource/Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Business_Alignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Service</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteRelatedRecords.cls
global with sharing class DeleteRelatedRecords{

    public static void RelatedLocation( set<id> LocIds){
        List<Location_Service__c> DeleteLocSerList = new List<Location_Service__c>();
        List<Resource_Service_Alignment__c> DeleteResourceList = new List<Resource_Service_Alignment__c>();
        List<Appointment__c> DeleteAppList = new List<Appointment__c>();
        Set<Id> AlignmentIds = new Set<Id>();
        List<Notification__c> noti = new List<Notification__c>();
        set<Id>appIds= new Set<Id>();
        
        if(Schema.sObjectType.Location_Service__c.fields.Location__c.isAccessible() && Schema.sObjectType.Location_Service__c.fields.Service__c.isAccessible()){
            DeleteLocSerList = [select Location__c,Service__c from Location_Service__c where Location__c IN: LocIds];
        }
        if(DeleteLocSerList.size() > 0){
            if(Location_Service__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteLocSerList;
            }
        }
        
        if(Schema.sObjectType.Resource_Service_Alignment__c.fields.Location__c.isAccessible() && Schema.sObjectType.Resource_Service_Alignment__c.fields.Service__c.isAccessible()
            && Schema.sObjectType.Resource_Service_Alignment__c.fields.Resource_Staff__c.isAccessible()){
            DeleteResourceList = [select Location__c,Resource_Staff__c,Service__c from Resource_Service_Alignment__c where Location__c IN: LocIds];
        }
        
        for(Resource_Service_Alignment__c ali : DeleteResourceList){
            AlignmentIds.add(ali.id);
        }
        if(Schema.sObjectType.Appointment__c.fields.Resource_Service_Alignment__c .isAccessible()){
            DeleteAppList = [select id,Resource_Service_Alignment__c from Appointment__c where Resource_Service_Alignment__c IN: AlignmentIds];
        }
        for(Appointment__c app: DeleteAppList){
            appIds.add(app.id);
        }
        if(Schema.sObjectType.Notification__c.fields.Appointment__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()){
            noti = [select id,Appointment__c,Contact__c from Notification__c where Appointment__c IN: appIds];
        }
        if(noti.size() > 0){
            if(Notification__c.sObjectType.getDescribe().isDeletable()){
                delete noti;
            }
        }
        if(DeleteAppList.size() > 0){
            if(Appointment__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteAppList;
            }
        }
        
        if(DeleteResourceList.size() > 0){
            if(Resource_Service_Alignment__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteResourceList;
            }
        }
    }
    
    public static void RelatedService( set<id> SerIds){
        List<Location_Service__c> DeleteLocSerList = new List<Location_Service__c>();
        List<Resource_Service_Alignment__c> DeleteResourceList = new List<Resource_Service_Alignment__c>();
        List<Appointment__c> DeleteAppList = new List<Appointment__c>();
        Set<Id> AlignmentIds = new Set<Id>();
        List<Notification__c> noti = new List<Notification__c>();
        set<Id>appIds= new Set<Id>();
        
        if(Schema.sObjectType.Location_Service__c.fields.Location__c.isAccessible() && Schema.sObjectType.Location_Service__c.fields.Service__c.isAccessible()){
            DeleteLocSerList = [select Location__c,Service__c from Location_Service__c where Service__c IN: SerIds];
        }
        if(DeleteLocSerList.size() > 0){
            if(Location_Service__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteLocSerList;
            }
        }
        
        if(Schema.sObjectType.Resource_Service_Alignment__c.fields.Location__c.isAccessible() && Schema.sObjectType.Resource_Service_Alignment__c.fields.Service__c.isAccessible()
            && Schema.sObjectType.Resource_Service_Alignment__c.fields.Resource_Staff__c.isAccessible()){
            DeleteResourceList = [select Location__c,Resource_Staff__c,Service__c from Resource_Service_Alignment__c where Service__c IN: SerIds];
        }
        for(Resource_Service_Alignment__c ali : DeleteResourceList){
            AlignmentIds.add(ali.id);
        }
        
        if(Schema.sObjectType.Appointment__c.fields.Resource_Service_Alignment__c .isAccessible()){
            DeleteAppList = [select id,Resource_Service_Alignment__c from Appointment__c where Resource_Service_Alignment__c IN: AlignmentIds];
        }
        for(Appointment__c app: DeleteAppList){
            appIds.add(app.id);
        }
        if(Schema.sObjectType.Notification__c.fields.Appointment__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()){
            noti = [select id,Appointment__c,Contact__c from Notification__c where Appointment__c IN: appIds];
        }
        if(noti.size() > 0){
            if(Notification__c.sObjectType.getDescribe().isDeletable()){
                delete noti;
            }
        }
        
        if(DeleteAppList.size() > 0){
            if(Appointment__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteAppList;
            }
        }
        
        if(DeleteResourceList.size() > 0){
            if(Resource_Service_Alignment__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteResourceList;
            }
        }
    }
    
    public static void RelatedResourcestaff( set<id> ResIds){
        List<Resource_Service_Alignment__c> DeleteResourceList = new List<Resource_Service_Alignment__c>();
        List<Appointment__c> DeleteAppList = new List<Appointment__c>();
        Set<Id> AlignmentIds = new Set<Id>();
        List<Notification__c> noti = new List<Notification__c>();
        set<Id>appIds= new Set<Id>();
        
        if(Schema.sObjectType.Location_Service__c.fields.Location__c.isAccessible() && Schema.sObjectType.Location_Service__c.fields.Service__c.isAccessible()){
            DeleteResourceList = [select Location__c,Resource_Staff__c,Service__c from Resource_Service_Alignment__c where Resource_Staff__c IN: ResIds];
        }
        for(Resource_Service_Alignment__c ali : DeleteResourceList){
            AlignmentIds.add(ali.id);
        }
        
        if(Schema.sObjectType.Appointment__c.fields.Resource_Service_Alignment__c .isAccessible()){
            DeleteAppList = [select id,Resource_Service_Alignment__c from Appointment__c where Resource_Service_Alignment__c IN: AlignmentIds];
        }
        for(Appointment__c app: DeleteAppList){
            appIds.add(app.id);
        }
        if(Schema.sObjectType.Notification__c.fields.Appointment__c.isAccessible() && Schema.sObjectType.Notification__c.fields.Contact__c.isAccessible()){
            noti = [select id,Appointment__c,Contact__c from Notification__c where Appointment__c IN: appIds];
        }
        if(noti.size() > 0){
            if(Notification__c.sObjectType.getDescribe().isDeletable()){
                delete noti;
            }
        }
        
        
        if(DeleteAppList.size() > 0){
            if(Appointment__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteAppList;
            }
        }
        
        if(DeleteResourceList.size() > 0){
            if(Resource_Service_Alignment__c.sObjectType.getDescribe().isDeletable()){
                delete DeleteResourceList;
            }
        }
    }
}