force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/All_Day_Event__c.field-meta.xml
<CustomField>
    <fullName>All_Day_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Day Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Resource_Service_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Resource_Service_Alignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource/Service Alignment</label>
    <referenceTo>Resource_Service_Alignment__c</referenceTo>
    <relationshipLabel>Resource/Service</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Upcoming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name__c</fullName>
    <label>Participant Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/Resource_Service_Alignment__c.object-meta.xml
<CustomObject>
    <label>Resource/Service Alignment</label>
    <nameField>
        <label>Resource/Service Alignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource/Service Alignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Resource/Service Alignments</relationshipLabel>
    <relationshipName>Resource_Service_Alignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Resource_Staff__c.field-meta.xml
<CustomField>
    <fullName>Resource_Staff__c</fullName>
    <label>Resource/Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Resource_Business_Alignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Service_Alignment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Service</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DashboardCtrl.cls
public with sharing class DashboardCtrl{
    
    public List<Appointment__c> appLIst{get;set;}
    public List<Appointment__c> appPastList{get;set;}
    public List<Appointment__c> appByService{get;set;} 
    public List<Participant__c> customerAppointment{get;set;}
    
    public map<string,List<appointment__c>> serviceMap{get;set;}
    public map<string,List<appointment__c>> locationMap{get;set;}
    public map<string,List<appointment__c>> customerMap{get;set;}
    
    public DashboardCtrl(){
        if (Schema.sObjectType.Appointment__c.fields.name.isAccessible() && Schema.sObjectType.Appointment__c.fields.Status__c.isAccessible() && Schema.sObjectType.Appointment__c.fields.Resource_Service_Alignment__c.isAccessible() && Schema.sObjectType.Resource_Service_Alignment__c.fields.Location__c.isAccessible()
            && Schema.sObjectType.Resource_Service_Alignment__c.fields.Service__c.isAccessible()  && Schema.sObjectType.Service__c.fields.Price__c.isAccessible()
            && Schema.sObjectType.Appointment__c.fields.Discount__c.isAccessible() && Schema.sObjectType.Resource_Service_Alignment__c.fields.Resource_Staff__c.isAccessible()
            && Schema.sObjectType.Appointment__c.fields.All_Day_Event__c.isAccessible() && Schema.sObjectType.Appointment__c.fields.Description__c.isAccessible()
            && Schema.sObjectType.Appointment__c.fields.Start_Date_Time__c.isAccessible() && Schema.sObjectType.Appointment__c.fields.End_Date_Time__c.isAccessible()){
                appList = new List<Appointment__c>();
                appLIst = [select name,Status__c,Resource_Service_Alignment__r.Location__c,Resource_Service_Alignment__r.Service__c,Resource_Service_Alignment__r.Service__r.Price__c,Discount__c,
                                           Resource_Service_Alignment__r.Resource_Staff__c,All_Day_Event__c,Description__c,Start_Date_Time__c,End_Date_Time__c
                                           from Appointment__c where DAY_ONLY(Start_Date_Time__c)>=: Date.Today()];
               
               appPastList = new List<Appointment__c>();
               appPastList = [select name,Status__c,Resource_Service_Alignment__r.Location__c,Resource_Service_Alignment__r.Service__c,Resource_Service_Alignment__r.Service__r.Price__c,Discount__c,
                                           Resource_Service_Alignment__r.Resource_Staff__c,All_Day_Event__c,Description__c,Start_Date_Time__c,End_Date_Time__c
                                           from Appointment__c where DAY_ONLY(Start_Date_Time__c) <=: Date.Today()];
              
              appByService = [select name,Status__c,Resource_Service_Alignment__r.Location__c,Resource_Service_Alignment__r.Location__r.street__c,Resource_Service_Alignment__r.Location__r.city__c,Resource_Service_Alignment__r.Service__c,Resource_Service_Alignment__r.Service__r.name,Resource_Service_Alignment__r.Service__r.Price__c,Discount__c,
                                           Resource_Service_Alignment__r.Resource_Staff__c,All_Day_Event__c,Description__c,Start_Date_Time__c,End_Date_Time__c,Resource_Service_Alignment__r.Location__r.name
                                           from Appointment__c where Start_Date_Time__c != null and DAY_ONLY(Start_Date_Time__c) >=: Date.Today()];                        
        }                      
        if(Schema.sObjectType.Participant__c.fields.Participant_Name__c.isAccessible() && Schema.sObjectType.Participant__c.fields.Appointment__c.isAccessible() && Schema.sObjectType.contact.fields.name.isAccessible()){
            customerAppointment =  [select id, Appointment__c, Participant_Name__c,Participant_Name__r.name from Participant__c where appointment__c != null];   
        }
                                   
      serviceMap = new map<string,List<appointment__c>>();
      locationMap = new map<string,List<appointment__c>>();
      
      for(appointment__c app : appByService){
          list<appointment__c> lst=serviceMap.get(app.Resource_Service_Alignment__r.Service__r.name);
          list<appointment__c> lstLoc = locationMap.get(app.Resource_Service_Alignment__r.Location__r.name);
           if(lst==null){
               lst=new list<appointment__c>();                
           }
           if(lstLoc == null){
               lstLoc = new list<appointment__c>();
           }
           lst.add(app);
           lstLoc.add(app);
           serviceMap.put(app.Resource_Service_Alignment__r.Service__r.name,lst);
           locationMap.put(app.Resource_Service_Alignment__r.Location__r.name, lstLoc);
      }
      set<id> setAppPartIds=new set<id>();
      for(Participant__c ap : customerAppointment ){
          setAppPartIds.add(ap.appointment__c);
      } 
      map<id,Appointment__c> mapApps=new map<id,Appointment__c>();
      if(Schema.sObjectType.Appointment__c.fields.name.isAccessible() && Schema.sObjectType.Appointment__c.fields.Start_Date_Time__c.isAccessible()){
          for(Appointment__c app: [select id ,name, Start_Date_Time__c from appointment__c where id in :setAppPartIds]){
              mapApps.put(app.id,app);
          }
      }
          
      customerMap  = new map<string,List<appointment__c>>();
      for(Participant__c par: customerAppointment){
          list<appointment__c> lst = customerMap.get(par.Participant_Name__r.name);
           if(lst==null){
               lst=new list<appointment__c>();                
           }
           lst.add(mapApps.get(par.Appointment__c));
         customerMap.put(par.Participant_Name__r.name,lst);
      }
      
    }
}